### PR TITLE
address deprecation of ruamel.yaml functions

### PR DESCRIPTION
**Pull request by RoyStegeman**
In 0.18.0 of `ruamel.yaml`, the old PyYAML functions have been deprecated. This PR updates to the new functionality that is there since version 0.15.0.

### CODE REVIEW

**Comment by scarlehoff** [comment]
Is this compatible with nnpdf? Because we are using yaml from reportengine

**Comment by scarlehoff** [comment]
Is this compatible with nnpdf? Because we are using yaml from reportengine

**Comment by RoyStegeman** [comment]
Yes compat.py will be broken with this since the syntax for yaml.ruamel has changed so we'd have to pin the reportengine version while we do these same changes on the nnpdf side

**Comment by scarlehoff** [comment]
Yes please, and then we merge both branches at the same time.

This should be fine since we are getting reportengine from github anyway (and branches in all PRs will need to be rebased but I'm perfectly fine with that :) )

**Pull request merged**
