### PR TITLE
[WIP] Add first draft of design

### PR DESCRIPTION
**Pull request by Zaharid**
Discuss general features of the framework, mostly based on the
experience of SMPDF. A few missing items are:

- Discussion on the looks of configuration files (for the report schema).

### CODE REVIEW

**Comment by Zaharid** [comment]
See doc at

https://github.com/NNPDF/reportengine/blob/designdocs/docs/DESIGN.md

**Comment by nhartland** [comment]
Just to check, under Script conventions, you mention:
"The name of the new resource will be the same as that of the function."
I guess there should also be some tag to specify which resource was used as input? For the cases
where one function is applied to several resources.

**Comment by nhartland** [comment]
Also, I think DAGResolver should probably be called something more like "ReportBuilder", as DAGResolver is a bit arcane and obfuscates a little the central purpose of the object.

**Comment by Zaharid** [comment]
Just to check, under Script conventions, you mention:
> "The name of the new resource will be the same as that of the function."
> I guess there should also be some tag to specify which resource was used
> as input? For the cases
> where one function is applied to several resources.
>
>
The way I see it is:
A function is a "resource provider" for the resource named as the function.
It takes a fixed set of parameters as input which correspond to the values
of the resources in that namespace. For example:

````python
def plot_arclengths(fit, arclengths) -> Figure:
````

Takes two resources called "fit" and "arclength", which will be resolved to
whatever they are in that namespace when the report is constructed. So in a
sense, the "tag" is the namespace.

**Comment by Zaharid** [comment]
Also, I think DAGResolver should probably be called something more like
> "ReportBuilder", as DAGResolver is a bit arcane and obfuscates a little the
> central purpose of the object.
>
The point is that it is more general than that. For example is something
that SMPDF could use instead of the current more primitive way of doing the
same thing, and not exactly to build a report... But I agree that
DAGResolver is a pretty horrible name...

**Comment by nhartland** [comment]
>Takes two resources called "fit" and "arclength", which will be resolved to
whatever they are in that namespace when the report is constructed. So in a
sense, the "tag" is the namespace.

This sounds a little restrictive on the resource provider to me.
Say you had three instances of the same resource type in a namespace and wanted to produce three resources via the same function. Of course you can resolve this by putting them in three different namespaces, but then you have the potential for the number of required namespaces to spiral quickly out of hand.

> The point is that it is more general than that. For example is something
that SMPDF could use instead of the current more primitive way of doing the
same thing, and not exactly to build a report... But I agree that
DAGResolver is a pretty horrible name...

Sure, how about "ResourceProcessor"?

**Comment by Zaharid** [comment]
On Thu, Sep 24, 2015 at 2:41 PM, Nathan Hartland <notifications@github.com>
wrote:

> Takes two resources called "fit" and "arclength", which will be resolved to
> whatever they are in that namespace when the report is constructed. So in a
> sense, the "tag" is the namespace.
>
> This sounds a little restrictive on the resource provider to me.
> Say you had three instances of the same resource type in a namespace and
> wanted to produce three resources via the same function. Of course you can
> resolve this by putting them in three different namespaces, but then you
> have the potential for the number of required namespaces to spiral quickly
> out of hand.
>
Agree. This is also a problem in SMPDF where to scan a parameter one has to
do things like

pdfsets:
   - MC900_nlo
actions:
   - smpdf
   - installgrids

actiongroups:
   - prefix: z05_
     smpdf_tolerance: 0.05

   - prefix: z10_
     smpdf_tolerance: 0.10

which becomes a little annoying. On the other hand, note that only the
things than change need to be specified. One solution I had in mind is a
directive to span namespaces from parameter values, something like:

actiongruop_for:
   vars: smpdf_tolerance: [0.05, 0.10]

so a little bit like a python list comprehension. But I'm not sure is the
easiest or best idea.

Sure, how about "ResourceProcessor"?
>

Yes, will change it :)

**Comment by nhartland** [comment]
Yeah, I'm not sure if namespaces are natural for this task. For example, if you wanted to do some ratio plots to something in the global namespace, you might want to do

```
globalfit=NNPDF3.0
namespace ratioplots{
    currentplot=MSTW08
    ratioplot(currentfit, globalfit)
    ratioplot(globalfit, currentfit)
}
```

Which in the current design would generate the same resource
Would it be easier to extend the resource name to include the arguments used?

I.e the calls

````
 ratioplot(currentfit, globalfit)
 ratioplot(globalfit, currentfit)
````

called from the namespace *NNPDF31* would generate a resources named
````
 "ratioplot:ratioplots.currentfit:globalfit"
 "ratioplot:globalfit:ratioplots.currentfit"
````

In this way you could also resolve resources generated in one namespace which use as input resources generated in the global scope.

**Comment by Zaharid** [comment]
The point of namespaces is to avoid "calling" the functions in the configuration. In the example above, the 'smpdf' line triggers a call (per namespace) to a function with a rather complicated signature, that the user does not need to be aware of.

Of course, this assumes that the functions will be called with the default arguments which can be directly mapped to resources (in fact it's done automatically).

**Comment by nhartland** [comment]
Alright, I think I understand the SMPDF behaviour a bit better then.
So the configuration you sketched above 
>pdfsets:
   - MC900_nlo
actions:
   - smpdf
   - installgrids
...

Would be a specification for the generation of resources, which the code later uses
in it's construction of (say) a report. Is that about right?

**Comment by Zaharid** [comment]
Yes.

The full configuration file is:

````yaml
fmt: png
observables:
   # Z
   - {name: 'data/z/z_13tev.root', order: 1} 
   - {name: 'data/z/z_lmpt_13tev.root', order: 1} 
   - {name: 'data/z/z_lmy_13tev.root', order: 1} 
   - {name: 'data/z/z_lplminvmass_13tev.root', order: 1} 
   - {name: 'data/z/z_lplmpt_13tev.root', order: 1}
   - {name: 'data/z/z_lppt_13tev.root', order: 1}
   - {name: 'data/z/z_lpy_13tev.root', order: 1}
   - {name: 'data/z/z_zpt_13tev.root', order: 1}
   - {name: 'data/z/z_zy_13tev.root', order: 1}

pdfsets:
   - MC900_nlo
actions:
   - smpdf
   - installgrids

actiongroups:
   - prefix: z05_
     smpdf_tolerance: 0.05

   - prefix: z10_
     smpdf_tolerance: 0.10

   - prefix: compall
     pdfsets:
        - z05_*
        - z10_*
        - MC900_nnlo
     actions:
        - violinplots
        - ciplots
        - savedata
     base_pdf: MC900_nnlo
````

Here the 'actiongroups'  run in order and execute the 'actions' (which are the global ones if not specified inside the actiongroup). 

In the first two actiongroups "SMPDFs" are generated with different parameters  (the action 'smpdf') and the moved to  LHAPDF (the action 'installgrids').

In the third group we change the pdf sets (which can be glob expanded :) ) and compute various plots which rely among other things on a resource "results" which is computed from the (local) pdfsets and the (global) observables.

**Comment by Zaharid** [comment]
A shortcoming of that design is that there is no separation between "resources" and "parameters" (simple values which affect on function such as smpdf_tolerance and thus have to be prefixed in a clumsy way). This can be done better here.

**Comment by nhartland** [comment]
Right, I guess for reportengine the actiongroups would be entirely specified
by the Report class after parsing the template report? Acting upon a set
of global variables specified in the input resource configuration?

**Comment by Zaharid** [comment]
The actiongroup's actions are in the report, while the remaining resources are the namespaces.
In this approach, the report would need to know in which namespace to execute each action.

**Comment by nhartland** [comment]
> The actiongroup's actions are in the report, while the remaining resources are the namespaces.
> In this approach, the report would need to know in which namespace to execute each action.
> 
Right, so the report requests that an action is performed in a specific namespace, and the
resulting *Resource* generated by that action is placed at that location in the report, OK.

I guess the namespaces are therefore defined along with input resources in some yml?

The way you assume the arguments for the actions does make me a bit nervous though.

For clarity it might be worthwhile specifying the target arguments in the report configuration.
(The signature for these actions should never be really that complicated by design).
That would solve the parameter-resource separation issue, and allow you to do the sorts
of manipulations I described above. The example of ratio plots with the numerator/denominator
switched around could be done much clearer, without any namespace gymnastics.

**Comment by nhartland** [comment]
To clarify, I agree the actions should be able to access the resources in the namespace they are executed in (and below) but I think we should also support extra arguments provided at the report level.

**Comment by nhartland** [comment]
(But then of course you need to add clarifying terms in the resource name)

**Comment by Zaharid** [comment]
On Thu, Sep 24, 2015 at 4:48 PM, Nathan Hartland <notifications@github.com>
wrote:

> > The actiongroup's actions are in the report, while the remaining
> resources are the namespaces.
> > In this approach, the report would need to know in which namespace to
> execute each action.
> >
> Right, so the report requests that an action is performed in a specific
> namespace, and the
> resulting *Resource* generated by that action is placed at that location
> in the report, OK.
>
> I guess the namespaces are therefore defined along with input resources in
> some yml?
>

Yes, that is sketched in the doc.


>
> The way you assume the arguments for the actions does make me a bit
> nervous though.
>
> For clarity it might be worthwhile specifying the target arguments in the
> report configuration.
> (The signature for these actions should never be really that complicated
> by design).
> That would solve the parameter-resource separation issue, and allow you to
> do the sorts
> of manipulations I described above. The example of ratio plots with the
> numerator/denominator
> switched around could be done much clearer, without any namespace
> gymnastics.
>

It is not obvious to me how the above example would look like in this
approach. For example 'violinplots' and 'ciplots' require a resource called
'results' that is not explicitly specified anywhere in the YAML (and is
precisely the point of having a ResourceProcesor aka DAGResolver).

**Comment by Zaharid** [comment]
...and are affected by

````
fmt: png
````

and

````
base_pdf: MC900_nlo
````

**Comment by nhartland** [comment]
> Yes, that is sketched in the doc.

OK, I see.

> It is not obvious to me how the above example would look like in this
> approach. For example 'violinplots' and 'ciplots' require a resource called
> 'results' that is not explicitly specified anywhere in the YAML (and is
> precisely the point of having a ResourceProcesor aka DAGResolver).

Well, certainly global settings such as figure format etc. can be accessible.

But in this scheme there would be no such resource called ‘results’ right?
If the resource is provided by the action ’smpdf’, then the resourcename would be 
‘smpdf’ which is explicitly in the YAML.

**Comment by nhartland** [comment]
> Well, certainly global settings such as figure format etc. can be accessible.

Although saying that, it may be better for them to be in another namespace
(global_settings) which can be passed also…..

**Comment by Zaharid** [comment]
There is a resource called 'results' because

1. It is an argument of one of the actions (say smpdf).
2. It exists as a resource provider in the user supplied module.

If 1. is true but not 2., then it's a error that would be caught in the checks.
Id 2. is true but not 1., then the resource is simply not computed because nobody requires it.

**Comment by nhartland** [comment]
So the idea is that if both 2. and 1. are true, then the stages are:

1. smpdf requests a resource “results”
2. ResourceProcessor finds no such resource, but finds a provider “results”
3. ResourceProcessor calls the provider “results” and passes it to smpdf

Is this about right?

**Comment by Zaharid** [comment]
Yes, exactly.

**Comment by nhartland** [comment]
OK, in which case, what is the namespace that the “results” provider should be called in?
You could do it automatically according to the namespace of the requesting action (global, in this case). 

But then I’d fear that you’d have to set up some very clear scoping rules, how would you handle
the action ’smpdf’ in a non-global namespace, when there is already a global ‘results’? The user
would have to know whether or not ‘results’ is recomputed for the non-global namespace or just
taken from the global one.

I’d worry that this would make it very easy to make mistakes on the user side.

**Comment by nhartland** [comment]
> I’d worry that this would make it very easy to make mistakes on the user side.

Specifically in that the scope in which automatically executed dependences are executed in
would be /implicit/ in the scoping rules and therefore not self-evident to the person writing
the report template.

>

**Comment by Zaharid** [comment]
Right. Actually in SMPDF there is not really a global namespace, but rather global variables that are inherited by the "actiongroups".

So in the end, each action is executed in an actiongroup and the results are those of the actiongroup.
In the special case where the ationgroup key is not present, everything behaves like one actiongroup. Therefore the scoping rules are unambiguous. 

To do the same, we could require that each resource is computed inside a namespace, so everything is recomputed always for each namespace (but nobody stops you from writing @functools.lru_cache above your function declarations if that makes sense for your application).

**Comment by nhartland** [comment]
> Right. Actually in SMPDF there is not really a global namespace, but rather global variables that are inherited by the "actiongroups".
> 
> So in the end, each action is executed in an actiongroup and the results are those of the actiongroup.
> In the special case where the ationgroup key is not present, everything behaves like one actiongroup. Therefore the scoping rules are unambiguous.
> 
Ok, good.
> To do the same, we could require that each resource is computed inside a namespace, so everything is recomputed always for each namespace (but nobody stops you from writing @functools.lru_cache above your function declarations if that makes sense for your application).
> 
Alright, so would it be possible to compare the resources in different actiongroups?
Say we’ve calculated arc lengths for two PDF sets, in this scheme the way to do that is to call the provider
‘arclength’ in two actiongroups (with different pdf names). I now want to plot both of them in the same figure.

If I understand correctly, the only way to do that in this configuration would be to write a new provider which
recomputes both arclengths in a new action group (which contains specific keywords to specify each PDF name).
I feel like this should be possible without having to recompute.

**Comment by nhartland** [comment]
I think in general here it’s very useful to separate the *resources* available
to a provider and the *arguments* supplied to it. 

In your scheme they are exactly the same thing, and this makes comparing
different resources more difficult than it needs to be.

**Comment by nhartland** [comment]
> I think in general here it’s very useful to separate the *resources* available
> to a provider and the *arguments* supplied to it. 

Sorry, by this I don't mean the resources available to a provider /during/ execution,
but rather the resources available for the provider to execute upon. If that makes sense.

> 
> In your scheme they are exactly the same thing, and this makes comparing
> different resources more difficult than it needs to be.
> 
>

**Comment by Zaharid** [comment]
Alright, so would it be possible to compare the resources in different
> actiongroups?
> Say we’ve calculated arc lengths for two PDF sets, in this scheme the way
> to do that is to call the provider
> ‘arclength’ in two actiongroups (with different pdf names). I now want to
> plot both of them in the same figure.
>
> If I understand correctly, the only way to do that in this configuration
> would be to write a new provider which
> recomputes both arclengths in a new action group (which contains specific
> keywords to specify each PDF name).
> I feel like this should be possible without having to recompute.
>


That's a good point.

A walkaround is having the resource providers be loop-aware. So 'arclength'
would be 'arclengths' and take a list of pdfs as an argument. So you
structure everything so that things that need to be compares are in the
same namespace. However this certainly wouldn't be straightforward  for all
cases...

**Comment by Zaharid** [comment]
For example, the action 'smpdf' which only makes sense for one pdfset at a time simply executes the "real smpdf" function once for each pdf in the pdfsets.  On the contrary, violinplots produces plots with all the pdfs together and produces one figure per observable.

**Comment by nhartland** [comment]
Right, but this has exactly the same problem just one step further down, the actions
have only one possible set of arguments (all the actiongroups).

Your workaround has the same problem as you mentioned before with the tolerances,  in that
you have to specify a whole different namespace for each possible combination of arc length
comparisons you need to do, which is pretty tedious.

I think the whole procedure would be fine if you are given the power to specify the namespace
in which dependences are executed. For example, you might have a configuration

basePDF:
	- name: NNPDF3.0
	actions:
		-pdfplots

refPDF:
	- name: NNPDF2.3
	actions:
		-pdfplots

Then you have a resourceprovider
	compareArcLengths
That depends on two 
	ArcLength
Resources.

In the report, you would specify that you wanted:
	compareArcLengths(“basePDF.ArcLength”, “refPDF.ArcLength”)
The ResourceProcessor would notice that the ArcLength resource is not available
in those two namespaces, and therefore call the ArcLength provider in both of those namespaces
before executing the compareArcLengths.

**Comment by Zaharid** [comment]
So there are the following conflicting requirements:

1. Complex things need to look simple to the user who fills the YAML file.
2. Adding new features has to be easy for the programmer of the client
library.
3. It should be possible to test the graph(s) for correctness assuming that
the nodes do the right thing.
4. There should be a sensible way to separate parameters to resources and
map both to providers.

In the current approach, I am happy with 1. and 3. and not so much with 2
and 4.

For example, at some point (now is simplified a little bit), specifying the
'smpdf' would trigger:
- parse pdfsets, observables.
- derive names of new grids and make them available for checking purposes
- compute "results(pdfsets,observables)"
- compute "correlation_results(results)"
- for each pdf in pdfsets: compute "real" smpdf(pdf, observables,
results[pdf], correlation_results[pdf[)

3. would become very difficult if one couldn't assume that results,
correlation_results and observables come from the same namespace.
1. would also be worse since the users would have to know about the steps
used to compute an smpdf instead of declaring that they want an smpdf and
have the engine do the rest.

As for 2, in this case there is no obvious way of avoiding the client code
do the " for each pdf in pdfsets:" because it also has to filter other
resources (in fact there is a result_table which can be indexed in many
ways for this reason). So I guess having this kind of loop somewhere in the
client code is part of the irreducible complexity of the problem, and to me
is better having it in the client code than in the configuration files. I
think we have to assume that providers will need to know how to deal with
arrays quite in general (and we may provide some helpers for that).

Finally for 4, creating a new namespace is not very nice (and relies on
clients caching everything), and also the semantics are not nice. Yet, I'm
inclined to think it's the right thing to do when mapping different
resources to the same provider (and so would correspond to a different
graph in general).

I'm thinking the following can be sensible:

Final nodes ("output resources")  are declared as:

def provider(*, resource1, resource2,..., param1=default1, param2=default2,
...):
and is called like provider(resource1=value1, resource2=value2,
param2=paramval2). The params are different from the resources in that they
have default values (thought this is an implementation detail). Since the
nodes are final, it is possible to call them with different params in
different parts of the report and they don't affect anything else (because
by specification they should not have side effects). We should think how
their return values populate the namespace if at all, but it's another
detail (maybe a dict indexed by paramvals).

If the nodes were nonfinal, they would probably still have to span a
namespace per parameter variation, but I think we can forbid that for the
moment (and probably doesn't have that many uses anyway, something like
'arclength' doesn't seem to need varying params). Therefore:

- Nonfinal nodes can be called with exactly one set of params per namespace.
- Final nodes can be called with any number of params.

What is final and nonfinal node is decided dynamically.

Does that make sense?

**Comment by nhartland** [comment]
> Final nodes ("output resources") are declared as:
> 
> def provider(*, resource1, resource2,..., param1=default1, param2=default2,
> �):

So for these, the list of resources is the same as usual (the inhabitants of their
namespace)? This makes sense for typical parameter variations, but it still makes life
difficult for arclength comparisons right? Because you need to call the arc length
provider on two input PDF sets. It�s not obvious to me how you�d do that here.

> different parts of the report and they don't affect anything else (because
> by specification they should not have side effects). We should think how
> their return values populate the namespace if at all, but it's another
> detail (maybe a dict indexed by paramvals).

I like the idea of adding the parameters to the resource name, as they should
completely specify the contents of that resource. I.e the whole
``` ResourceName:param1:param2 ```

Furthermore they then do not need to be only output resources, as other providers
can reference them by that name. I do agree that for most cases, the intermediate
resources should only be called with default arguments. I just think that allowing
for arguments in intermediate resources is a useful tool for �power-users�.

> If the nodes were nonfinal, they would probably still have to span a
> namespace per parameter variation, but I think we can forbid that for the
> moment (and probably doesn't have that many uses anyway, something like
> 'arclength' doesn't seem to need varying params). Therefore:

I don�t see why they /have/ to span a whole namespace per parameter variation,
as they can take resource names as I sketched above. Once again though I do agree
that for the most part this is an advanced feature.

> - Nonfinal nodes can be called with exactly one set of params per namespace.
> - Final nodes can be called with any number of params.
> 
> What is final and nonfinal node is decided dynamically.
> 
> Does that make sense?

**Comment by nhartland** [comment]
> 1. Complex things need to look simple to the user who fills the YAML file.

I guess the main point of my disagreement is in this point, which I don’t think is such a strenuous requirement.
I think simple things should look simple to the user, but complex things should look *clear* rather than simple.

> 2. Adding new features has to be easy for the programmer of the client
> library.
> 3. It should be possible to test the graph(s) for correctness assuming that
> the nodes do the right thing.
> 4. There should be a sensible way to separate parameters to resources and
> map both to providers.
> 
> In the current approach, I am happy with 1. and 3. and not so much with 2
> and 4.
> 
> For example, at some point (now is simplified a little bit), specifying the
> 'smpdf' would trigger:
> - parse pdfsets, observables.
> - derive names of new grids and make them available for checking purposes
> - compute "results(pdfsets,observables)"
> - compute "correlation_results(results)"
> - for each pdf in pdfsets: compute "real" smpdf(pdf, observables,
> results[pdf], correlation_results[pdf[)
> 
> 3. would become very difficult if one couldn't assume that results,
> correlation_results and observables come from the same namespace.
> 1. would also be worse since the users would have to know about the steps
> used to compute an smpdf instead of declaring that they want an smpdf and
> have the engine do the rest.
> 
> As for 2, in this case there is no obvious way of avoiding the client code
> do the " for each pdf in pdfsets:" because it also has to filter other
> resources (in fact there is a result_table which can be indexed in many
> ways for this reason). So I guess having this kind of loop somewhere in the
> client code is part of the irreducible complexity of the problem, and to me
> is better having it in the client code than in the configuration files. I
> think we have to assume that providers will need to know how to deal with
> arrays quite in general (and we may provide some helpers for that).
> 
> Finally for 4, creating a new namespace is not very nice (and relies on
> clients caching everything), and also the semantics are not nice. Yet, I'm
> inclined to think it's the right thing to do when mapping different
> resources to the same provider (and so would correspond to a different
> graph in general).
> 
> I'm thinking the following can be sensible:
> 
> Final nodes ("output resources") are declared as:
> 
> def provider(*, resource1, resource2,..., param1=default1, param2=default2,
> ...):
> and is called like provider(resource1=value1, resource2=value2,
> param2=paramval2). The params are different from the resources in that they
> have default values (thought this is an implementation detail). Since the
> nodes are final, it is possible to call them with different params in
> different parts of the report and they don't affect anything else (because
> by specification they should not have side effects). We should think how
> their return values populate the namespace if at all, but it's another
> detail (maybe a dict indexed by paramvals).
> 
> If the nodes were nonfinal, they would probably still have to span a
> namespace per parameter variation, but I think we can forbid that for the
> moment (and probably doesn't have that many uses anyway, something like
> 'arclength' doesn't seem to need varying params). Therefore:
> 
> - Nonfinal nodes can be called with exactly one set of params per namespace.
> - Final nodes can be called with any number of params.
> 
> What is final and nonfinal node is decided dynamically.
> 
> Does that make sense?
> 
> On Thu, Sep 24, 2015 at 7:08 PM, Nathan Hartland <notifications@github.com>
> wrote:
> 
> > Right, but this has exactly the same problem just one step further down,
> > the actions
> > have only one possible set of arguments (all the actiongroups).
> >
> > Your workaround has the same problem as you mentioned before with the
> > tolerances, in that
> > you have to specify a whole different namespace for each possible
> > combination of arc length
> > comparisons you need to do, which is pretty tedious.
> >
> > I think the whole procedure would be fine if you are given the power to
> > specify the namespace
> > in which dependences are executed. For example, you might have a
> > configuration
> >
> > basePDF:
> > - name: NNPDF3.0
> > actions:
> > -pdfplots
> >
> > refPDF:
> > - name: NNPDF2.3
> > actions:
> > -pdfplots
> >
> > Then you have a resourceprovider
> > compareArcLengths
> > That depends on two
> > ArcLength
> > Resources.
> >
> > In the report, you would specify that you wanted:
> > compareArcLengths(“basePDF.ArcLength”, “refPDF.ArcLength”)
> > The ResourceProcessor would notice that the ArcLength resource is not
> > available
> > in those two namespaces, and therefore call the ArcLength provider in both
> > of those namespaces
> > before executing the compareArcLengths.
> >
> > > On 24 Sep 2015, at 17:46, Zaharid <notifications@github.com <mailto:

**Comment by Zaharid** [comment]
>
> So for these, the list of resources is the same as usual (the inhabitants
> of their
> namespace)? This makes sense for typical parameter variations, but it
> still makes life
> difficult for arclength comparisons right? Because you need to call the
> arc length
> provider on two input PDF sets. It�s not obvious to me how you�d do that
> here.


As said, since the merging operation has to be done somewhere, I like it
more in the code than in the configuration. Since different resources need
to do different operations on the data, they need to group it differently,
so I'd say the (intermediate) resources have to  general operate on list of
things in general. For an example of many different ways you would like to
group in different resources see eg:

https://github.com/scarrazza/smpdf/blob/master/src/smpdflib/plots.py#L131


On Fri, Sep 25, 2015 at 4:02 PM, Nathan Hartland <notifications@github.com>
wrote:

>
> I like the idea of adding the parameters to the resource name, as they
> should
> completely specify the contents of that resource. I.e the whole
> ``` ResourceName:param1:param2 ```
>
> Furthermore they then do not need to be only output resources, as other
> providers
> can reference them by that name. I do agree that for most cases, the
> intermediate
> resources should only be called with default arguments. I just think that
> allowing
> for arguments in intermediate resources is a useful tool for �power-users�.
>

I believe that's difficult for the reason illustrated in the example above:
If a provider cannot assume that all its reosurces play well together, a
lot of checking that is trivial to do would be impossible or very
cumbersome. For example, SMPDF checks that pdf and observables are OK, and
therefore the results have to be. If you can change the pdfs and the
observables incoherently at arbitrary parts, this is not easy to guatantee
(in other words it "breaks invariants").

**Comment by nhartland** [comment]
> I believe that's difficult for the reason illustrated in the example above:
> If a provider cannot assume that all its reosurces play well together, a
> lot of checking that is trivial to do would be impossible or very
> cumbersome. For example, SMPDF checks that pdf and observables are OK, and
> therefore the results have to be. If you can change the pdfs and the
> observables incoherently at arbitrary parts, this is not easy to guatantee
> (in other words it "breaks invariants”).

Sure, I can buy that it can lead to situations where you have incompatible
inputs, say if you had a combined arclength and pdf plot and accidentally
called the wrong resources:

`` arclen_pdfplot(“arclength:NNPDF3.0”:”pdf:NNPDF2.3”) ``

But you still have the automatic check at the level of Resource type (i,e arc length and pdf).
And I think at some point you have to trust the user to arrange things correctly!

I do think that it’s worth the reduced safety for the increased flexibilty. After all, the
above statement is very clear and if the resources don’t play together properly
we can safely conclude that is entirely the fault of the user :)

**Comment by nhartland** [comment]
But alright, I do think that at least being able to specify parameters for final output resources is useful.
And if there is a structure available to do that then we have the option of extending it further in the future if we think it's neccesary (after trying a few test implementations).

**Comment by Zaharid** [comment]
OK, then for the time being:

- Final resources can be called with any parameters.
- For now, nonfinal need to be called in a different namespace if their
parameters change (so one gets certain properties of the graph for free).
- The precise way of how you do things like compare_arclengths() is to be
decided after evaluating several posibilities. I lean towards the approach
where arclengths() computes all the possible arclengths but it may be not
the best.

There is to be decided:
-The format of the schema
And related,
-The syntax and precise definition of "parameters".

**Comment by nhartland** [comment]
> - Final resources can be called with any parameters.
> - For now, nonfinal need to be called in a different namespace if their
> parameters change (so one gets certain properties of the graph for free).
> - The precise way of how you do things like compare_arclengths() is to be
> decided after evaluating several posibilities. I lean towards the approach
> where arclengths() computes all the possible arclengths but it may be not
> the best.

Right, sounds good. I agree that we could do with trying out a few
options in practice.

**Comment by scarrazza** [comment]
Hi guys, please take a look at the design layout graph here:
https://github.com/NNPDF/reportengine/blob/designdocs/docs/reportengine_layout.pdf

We should think more about the "Report Builder" location.

**Comment by Zaharid** [comment]
On Fri, Sep 25, 2015 at 6:25 PM, Stefano Carrazza <notifications@github.com>
wrote:

>
> We should think more about the "Report Builder" location.
>
> I'd say it goes like this: The report class has methods to read the
template (whatever that is), extract required resources from the template
(+params) and fill the template with the values of the resources, to
produce the final output. Ot also manages the io (ie a reportengine.Figure)
is allocated a correct path and saved when the report is to be built.

**Comment by Zaharid** [comment]
I have updated the text. After discussing with Stefano, I don't really see good reasons not to use jinja2 (and the API can provide what we want by playing with the AST) so I think we all agree.

If it's OK with everybody, we can merge this and start going. I'd say there is enough path clear in there to start with the basic structure, until we have to rethink things.

**Comment by scarrazza** [comment]
Yeah, I fully agree. I think the current layout is clear enough to try a 
first implementation.

**Comment by nhartland** [comment]
Just took a look at the new document, Sounds good to me!

**Pull request merged**
